# Generated by Django 2.2 on 2020-03-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracktool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='registered name', max_length=20)),
                ('priority', models.CharField(choices=[('1', 'priority and important'), ('2', 'picked in resolved in 60 min time'), ('3', 'picked in 2 hrs'), ('4', 'picked in 12 hrs'), ('5', '24 hrs priority')], help_text='1 is most prioritised', max_length=2)),
                ('issue', models.CharField(choices=[('sl', 'software relate'), ('hw', 'hardware relate'), ('Nw', 'Network relate')], help_text='select related', max_length=50)),
                ('discription', models.TextField(help_text='elaberate the issue', max_length=300)),
                ('status', models.CharField(choices=[('op', 'open'), ('as', 'assigned'), ('INP', 'Inprogress'), ('cl', 'closed'), ('fw', 'changedepartment')], help_text='status', max_length=3)),
                ('attachments', models.ImageField(upload_to='images/')),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
