# Generated by Django 2.2 on 2020-03-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracktool', '0002_auto_20200308_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='attachments',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
