# Generated by Django 2.2 on 2020-03-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracktool', '0004_auto_20200315_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='name',
            field=models.CharField(help_text='registered name', max_length=20),
        ),
    ]
