# Generated by Django 2.2 on 2020-03-15 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracktool', '0006_auto_20200315_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='name',
            field=models.ForeignKey(help_text='User liked the post', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
